name: main

on:
  push:
    branches: []
    tags: []
  pull_request:
    branches: []

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - name: Check if .Libplanet refers to a tagged commit
      if: |
        github.event_name == 'push' && (
          github.ref == 'refs/heads/main' ||
          startsWith(github.ref, 'refs/heads/rc-') ||
          startsWith(github.ref, 'refs/tags/')
        ) ||
        github.event_name == 'pull_request' && (
          github.head_ref == 'refs/heads/main' ||
          startsWith(github.head_ref, 'refs/heads/rc-') ||
          startsWith(github.head_ref, 'refs/tags/')
        )
      run: |
        set -e
        pushd .Libplanet/
        git fetch origin 'refs/tags/*:refs/tags/*'
        if ! git describe --tags --exact-match; then
          echo "The unreleased Libplanet shouldn't be used." > /dev/stderr
          exit 1
        fi
        popd
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.403
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release
    - name: Test
      run: dotnet test --no-restore --verbosity normal
